export const billResponse = {
  getAirtimePlan: { statusCode: 200, message: 'Airtime plan fetched successfully', data: [{ id: 1, amount: 100 }] },
  getAirtimeNetworkProviders: { statusCode: 200, message: 'Airtime network providers fetched successfully', data: [{ id: 1, name: 'MTN' }] },
  getDataNetworkProviders: { statusCode: 200, message: 'Data plans by network fetched successfully', data: [{ id: 1, name: '1GB Weekly' }] },
  getInternationalAirtimePlan: { statusCode: 200, message: 'International airtime plans fetched successfully', data: [{ id: 1, amount: 10, currency: 'USD' }] },
  getAirtimeFxRate: { statusCode: 200, message: 'Airtime FX rate fetched successfully', data: { rate: 1550, amount: 10 } },
  getDataPlan: { statusCode: 200, message: 'Data plans fetched successfully', data: [{ id: 1, name: '2GB Monthly' }] },
  getCabelPlan: { statusCode: 200, message: 'Cable plans fetched successfully', data: [{ id: 1, name: 'DSTV Compact' }] },
  getElectricityPlan: { statusCode: 200, message: 'Electricity plans fetched successfully', data: [{ id: 1, name: 'Prepaid' }] },
  getInternetPlan: { statusCode: 200, message: 'Internet plans fetched successfully', data: [{ id: 1, name: 'Fiber Basic' }] },
  getTransportPlan: { statusCode: 200, message: 'Transport plans fetched successfully', data: [{ id: 1, name: 'BRT Pass' }] },
  getSchoolfeePlan: { statusCode: 200, message: 'School fee plans fetched successfully', data: [{ id: 1, name: 'Session Payment' }] },
  getAirtimeVariation: { statusCode: 200, message: 'Airtime variations fetched successfully', data: [{ code: 'mtn_vtu' }] },
  getDataVariation: { statusCode: 200, message: 'Data variations fetched successfully', data: [{ code: 'mtn_data' }] },
  dataPay: { statusCode: 200, message: 'Data purchase successful', data: { transactionId: 'txn_1001', status: 'SUCCESS' } },
  airtimePay: { statusCode: 200, message: 'Airtime purchase successful', data: { transactionId: 'txn_1002', status: 'SUCCESS' } },
  internationalAirtimePay: { statusCode: 200, message: 'International airtime purchase successful', data: { transactionId: 'txn_1003', status: 'SUCCESS' } },
  getGiftCardCategories: { statusCode: 200, message: 'Gift card categories fetched successfully', data: [{ id: 1, name: 'Amazon' }] },
  getProductByISOCode: { statusCode: 200, message: 'Gift card products fetched successfully', data: [{ id: 1, name: 'Amazon US $50' }] },
  getGiftCardFxRate: { statusCode: 200, message: 'Gift card FX rate fetched successfully', data: { rate: 1520, amount: 50 } },
  getCableBillInfo: { statusCode: 200, message: 'Cable bill info fetched successfully', data: { billerCode: 'dstv', hasVariation: true } },
  getElectricityBillInfo: { statusCode: 200, message: 'Electricity bill info fetched successfully', data: { billerCode: 'ikeja', hasVariation: true } },
  getInternetBillInfo: { statusCode: 200, message: 'Internet bill info fetched successfully', data: { billerCode: 'smile', hasVariation: true } },
  getTransportBillInfo: { statusCode: 200, message: 'Transport bill info fetched successfully', data: { billerCode: 'brt', hasVariation: true } },
  getSchoolfeeBillInfo: { statusCode: 200, message: 'School fee bill info fetched successfully', data: { billerCode: 'school', hasVariation: true } },
  verifyCableNumber: { statusCode: 201, message: 'Cable number verified successfully', data: { customerName: 'John Doe' } },
  verifyMeterNumber: { statusCode: 201, message: 'Meter number verified successfully', data: { customerName: 'John Doe' } },
  cablePay: { statusCode: 201, message: 'Cable payment successful', data: { transactionId: 'txn_1004', status: 'SUCCESS' } },
  electricityPay: { statusCode: 201, message: 'Electricity payment successful', data: { transactionId: 'txn_1005', status: 'SUCCESS' } },
  giftcardPay: { statusCode: 201, message: 'Gift card purchase successful', data: { transactionId: 'txn_1006', status: 'SUCCESS' } },
  getGiftCardRedeemCode: { statusCode: 200, message: 'Gift card redeem code fetched successfully', data: { code: 'ABCD-EFGH-IJKL' } },
  getBeneficiaries: { statusCode: 200, message: 'Bill beneficiaries fetched successfully', data: [{ id: 'bnf_001', name: 'Jane Doe' }] },
  internetPay: { statusCode: 201, message: 'Internet payment successful', data: { transactionId: 'txn_1007', status: 'SUCCESS' } },
  transportPay: { statusCode: 201, message: 'Transport payment successful', data: { transactionId: 'txn_1008', status: 'SUCCESS' } },
  schoolfeePay: { statusCode: 201, message: 'School fee payment successful', data: { transactionId: 'txn_1009', status: 'SUCCESS' } },
} as const;
