export const loanResourceResponse = {
  getCategories: {
    statusCode: 200,
    message: 'Categories retrieved',
    data: [
      { id: 'cat-uuid-001', name: 'Seeds', description: 'Crop seeds for planting', imageUrl: null, isActive: true },
      { id: 'cat-uuid-002', name: 'Fertilizers', description: 'Soil enrichment products', imageUrl: null, isActive: true },
    ],
  },
  createCategory: {
    statusCode: 201,
    message: 'Category created',
    data: { id: 'cat-uuid-003', name: 'Irrigation', description: 'Irrigation materials', imageUrl: null, isActive: true },
  },
  getResources: {
    statusCode: 200,
    message: 'Resources retrieved',
    data: [
      {
        id: 'res-uuid-001',
        categoryId: 'cat-uuid-001',
        name: 'Maize Seeds (OPV)',
        description: 'Open-pollinated variety maize seeds suitable for tropical climates',
        imageUrl: null,
        unitPrice: 3500,
        unitOfMeasure: 'bag',
        stockQuantity: 200,
        minQuantity: 1,
        supplier: 'AgroSeeds Ltd',
        suitableCrops: 'Maize',
        isEligibleForLoan: true,
        isActive: true,
        category: { id: 'cat-uuid-001', name: 'Seeds' },
      },
    ],
    meta: { total: 1, page: 1, limit: 20, pages: 1 },
  },
  getResource: {
    statusCode: 200,
    message: 'Resource retrieved',
    data: {
      id: 'res-uuid-001',
      categoryId: 'cat-uuid-001',
      name: 'Maize Seeds (OPV)',
      description: 'Open-pollinated variety maize seeds suitable for tropical climates',
      imageUrl: null,
      unitPrice: 3500,
      unitOfMeasure: 'bag',
      stockQuantity: 200,
      minQuantity: 1,
      supplier: 'AgroSeeds Ltd',
      suitableCrops: 'Maize',
      isEligibleForLoan: true,
      isActive: true,
      category: { id: 'cat-uuid-001', name: 'Seeds' },
    },
  },
  createResource: {
    statusCode: 201,
    message: 'Resource created',
    data: {
      id: 'res-uuid-002',
      categoryId: 'cat-uuid-002',
      name: 'Urea Fertilizer',
      unitPrice: 22000,
      unitOfMeasure: 'bag',
      stockQuantity: 500,
      minQuantity: 1,
      supplier: 'FertilizeNG',
      isEligibleForLoan: true,
      isActive: true,
    },
  },
  updateResource: {
    statusCode: 200,
    message: 'Resource updated',
    data: {
      id: 'res-uuid-001',
      name: 'Maize Seeds (OPV)',
      unitPrice: 3800,
      stockQuantity: 180,
      isActive: true,
    },
  },
} as const;
