export const farmResponse = {
  getMyFarms: {
    statusCode: 200,
    message: 'Farms retrieved',
    data: [
      {
        id: 'farm-uuid-001',
        userId: 'user-uuid-001',
        name: 'Abubakar North Farm',
        address: 'Along Zaria Road, Kankia',
        state: 'Katsina',
        lga: 'Kankia',
        ward: 'Gafai',
        latitude: 12.8543,
        longitude: 7.6312,
        sizeValue: 5,
        sizeUnit: 'hectares',
        ownershipType: 'owned',
        mainCropType: 'Maize',
        secondaryCropType: 'Sorghum',
        farmingSeason: '2026 Wet Season',
        expectedPlantingDate: '2026-05-01',
        expectedHarvestDate: '2026-09-30',
        hasIrrigation: false,
        isVerified: false,
        photos: [],
        createdAt: '2026-04-10T08:00:00.000Z',
      },
    ],
  },
  getFarm: {
    statusCode: 200,
    message: 'Farm retrieved',
    data: {
      id: 'farm-uuid-001',
      userId: 'user-uuid-001',
      name: 'Abubakar North Farm',
      address: 'Along Zaria Road, Kankia',
      state: 'Katsina',
      lga: 'Kankia',
      ward: 'Gafai',
      latitude: 12.8543,
      longitude: 7.6312,
      sizeValue: 5,
      sizeUnit: 'hectares',
      ownershipType: 'owned',
      mainCropType: 'Maize',
      secondaryCropType: 'Sorghum',
      farmingSeason: '2026 Wet Season',
      hasIrrigation: false,
      isVerified: false,
      photos: [{ id: 'photo-uuid-001', url: 'https://cdn.ubi.ng/farms/photo1.jpg' }],
    },
  },
  createFarm: {
    statusCode: 201,
    message: 'Farm created',
    data: {
      id: 'farm-uuid-002',
      userId: 'user-uuid-001',
      name: 'Southern Cassava Plot',
      state: 'Ogun',
      lga: 'Ijebu-Ode',
      sizeValue: 2.5,
      sizeUnit: 'hectares',
      ownershipType: 'leased',
      mainCropType: 'Cassava',
      hasIrrigation: false,
      isVerified: false,
      photos: [],
    },
  },
  updateFarm: {
    statusCode: 200,
    message: 'Farm updated',
    data: {
      id: 'farm-uuid-001',
      name: 'Abubakar North Farm (Updated)',
      sizeValue: 6,
      farmingSeason: '2026 Wet Season',
    },
  },
  addPhoto: {
    statusCode: 201,
    message: 'Photo added',
    data: { id: 'photo-uuid-002', farmId: 'farm-uuid-001', url: 'https://cdn.ubi.ng/farms/photo2.jpg', filename: 'field-view.jpg' },
  },
} as const;
