version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:2024.05.1

    working_directory: ~/app

    steps:
      # Checkout repo
      - checkout

      # Restore cache for dependencies
      - restore_cache:
          keys:
            - app-{{ checksum "package.json" }}

      # Login to DockerHub
      - run:
          name: Setting up Docker
          command: |
            echo "$DOCKER_PASS" | docker login --username "$DOCKER_USER" --password-stdin

      # Build & Push using Dockerfile
      - run:
          name: Build and push to DockerHub (AWS Dockerfile)
          command: |
            docker build -f Dockerfile --build-arg DATABASE_URL=$DATABASE_URL -t aliyura/ubi-backend:latest .
            docker push aliyura/ubi-backend:latest
