export const loanApplicationResponse = {
  eligibilityCheck: {
    statusCode: 200,
    message: 'Eligibility check completed',
    data: {
      eligible: 'pass',
      checks: [
        { checkName: 'KYC Verification', result: 'pass', note: 'KYC tier is sufficient' },
        { checkName: 'Active Loan Conflict', result: 'pass', note: 'No conflicting loan found' },
        { checkName: 'Farm Exists', result: 'pass', note: 'Farm record found' },
        { checkName: 'Cart Not Empty', result: 'pass', note: 'Cart has items' },
        { checkName: 'Repayment History', result: 'pass', note: 'No overdue repayments' },
        { checkName: 'Contact Verification', result: 'pass', note: 'Phone and email are verified' },
      ],
      blockingIssues: [],
      warnings: [],
    },
  },
  eligibilityCheckFailed: {
    statusCode: 400,
    message: 'Eligibility check failed',
    errors: [
      { field: 'eligibility', message: 'Please complete KYC tier 2 or higher' },
      { field: 'eligibility', message: 'You have an active application UBI-2026-XYZ that must be resolved first' },
    ],
    data: {
      eligible: 'fail',
      checks: [],
      blockingIssues: ['Please complete KYC tier 2 or higher'],
      warnings: [],
    },
  },
  submit: {
    statusCode: 201,
    message: 'Loan application submitted successfully',
    data: {
      id: 'app-uuid-001',
      applicationRef: 'UBI-2026-AB3CD7E',
      userId: 'user-uuid-001',
      farmId: 'farm-uuid-001',
      status: 'Submitted',
      totalEstimatedValue: 61500,
      currency: 'NGN',
      purpose: 'Wet season maize planting',
      season: '2026 Wet Season',
      fulfillmentMethod: 'delivery',
      submittedAt: '2026-04-18T10:30:00.000Z',
      eligibility: { eligible: 'pass', blockingIssues: [], warnings: [] },
    },
  },
  getMyApplications: {
    statusCode: 200,
    message: 'Applications retrieved',
    data: [
      {
        id: 'app-uuid-001',
        applicationRef: 'UBI-2026-AB3CD7E',
        status: 'Submitted',
        totalEstimatedValue: 61500,
        submittedAt: '2026-04-18T10:30:00.000Z',
        farm: { name: 'Abubakar North Farm', state: 'Katsina' },
        items: [
          { itemName: 'Maize Seeds (OPV)', quantity: 5, unitPrice: 3500, totalAmount: 17500 },
          { itemName: 'Urea Fertilizer', quantity: 2, unitPrice: 22000, totalAmount: 44000 },
        ],
      },
    ],
    meta: { total: 1, page: 1, limit: 20, pages: 1 },
  },
  getApplication: {
    statusCode: 200,
    message: 'Application retrieved',
    data: {
      id: 'app-uuid-001',
      applicationRef: 'UBI-2026-AB3CD7E',
      status: 'UnderReview',
      totalEstimatedValue: 61500,
      currency: 'NGN',
      purpose: 'Wet season maize planting',
      season: '2026 Wet Season',
      fulfillmentMethod: 'delivery',
      deliveryAddress: 'No 4 Kankia Road, Katsina',
      submittedAt: '2026-04-18T10:30:00.000Z',
      farm: {
        id: 'farm-uuid-001',
        name: 'Abubakar North Farm',
        state: 'Katsina',
        lga: 'Kankia',
        mainCropType: 'Maize',
        sizeValue: 5,
        sizeUnit: 'hectares',
        photos: [],
      },
      items: [
        { itemName: 'Maize Seeds (OPV)', quantity: 5, unitPrice: 3500, totalAmount: 17500 },
        { itemName: 'Urea Fertilizer', quantity: 2, unitPrice: 22000, totalAmount: 44000 },
      ],
      eligibilityChecks: [
        { checkName: 'KYC Verification', result: 'pass' },
        { checkName: 'Active Loan Conflict', result: 'pass' },
      ],
      decisions: [],
      statusHistory: [
        { toStatus: 'Submitted', changedBy: 'user-uuid-001', createdAt: '2026-04-18T10:30:00.000Z' },
        { toStatus: 'EligibilityReview', changedBy: 'system', createdAt: '2026-04-18T10:31:00.000Z' },
        { toStatus: 'UnderReview', changedBy: 'admin-uuid-001', createdAt: '2026-04-18T11:00:00.000Z' },
      ],
      fulfillment: null,
      repaymentPlan: null,
    },
  },
  getTimeline: {
    statusCode: 200,
    message: 'Timeline retrieved',
    data: [
      { id: 'hist-001', fromStatus: null, toStatus: 'Submitted', changedBy: 'user-uuid-001', reason: 'Application submitted by farmer', createdAt: '2026-04-18T10:30:00.000Z' },
      { id: 'hist-002', fromStatus: 'Submitted', toStatus: 'EligibilityReview', changedBy: 'system', reason: null, createdAt: '2026-04-18T10:31:00.000Z' },
      { id: 'hist-003', fromStatus: 'EligibilityReview', toStatus: 'UnderReview', changedBy: 'admin-uuid-001', reason: 'Passed eligibility checks', createdAt: '2026-04-18T11:00:00.000Z' },
    ],
  },
  getRepaymentSchedule: {
    statusCode: 200,
    message: 'Repayment schedule retrieved',
    data: {
      id: 'plan-uuid-001',
      applicationId: 'app-uuid-001',
      principalEquivalent: 61500,
      serviceCharge: 3075,
      totalRepaymentAmount: 64575,
      repaymentFrequency: 'monthly',
      numberOfInstallments: 6,
      installmentAmount: 10762.5,
      firstDueDate: '2026-10-01',
      amountRepaid: 0,
      outstandingBalance: 64575,
      status: 'pending',
      repayments: [
        { installmentNumber: 1, dueDate: '2026-10-01', amount: 10762.5, status: 'pending' },
        { installmentNumber: 2, dueDate: '2026-11-01', amount: 10762.5, status: 'pending' },
        { installmentNumber: 3, dueDate: '2026-12-01', amount: 10762.5, status: 'pending' },
        { installmentNumber: 4, dueDate: '2027-01-01', amount: 10762.5, status: 'pending' },
        { installmentNumber: 5, dueDate: '2027-02-01', amount: 10762.5, status: 'pending' },
        { installmentNumber: 6, dueDate: '2027-03-01', amount: 10762.5, status: 'pending' },
      ],
    },
  },
  cancel: {
    statusCode: 200,
    message: 'Application cancelled',
    data: null,
  },
} as const;
