export const loanApplicationResponse = {
  eligibilityCheck: {
    statusCode: 200,
    message: 'Eligibility check completed',
    data: {
      eligible: 'pass',
      checks: [
        {
          checkName: 'KYC Verification',
          result: 'pass',
          note: 'KYC tier is sufficient',
        },
        {
          checkName: 'Active Loan Conflict',
          result: 'pass',
          note: 'No conflicting loan found',
        },
        { checkName: 'Farm Exists', result: 'pass', note: 'Farm record found' },
        { checkName: 'Cart Not Empty', result: 'pass', note: 'Cart has items' },
        {
          checkName: 'Repayment History',
          result: 'pass',
          note: 'No overdue repayments',
        },
        {
          checkName: 'Contact Verification',
          result: 'pass',
          note: 'Phone and email are verified',
        },
      ],
      blockingIssues: [],
      warnings: [],
    },
  },
  eligibilityCheckFailed: {
    statusCode: 200,
    status: false,
    message: 'You are not eligible to apply for a loan at this time',
    data: {
      eligible: 'fail',
      blockingIssues: [
        'Please complete KYC tier 2 or higher',
        'You have an active application (UBI-2026-XYZ) that must be resolved first',
      ],
      warnings: [],
      checks: [
        {
          checkName: 'KYC Verification',
          result: 'fail',
          note: 'Please complete KYC tier 2 or higher',
          source: 'system',
        },
        {
          checkName: 'Active Loan Conflict',
          result: 'fail',
          note: 'You have an active application (UBI-2026-XYZ) that must be resolved first',
          source: 'system',
        },
        {
          checkName: 'Farm Exists',
          result: 'pass',
          note: 'Farm record found',
          source: 'system',
        },
        {
          checkName: 'Cart Not Empty',
          result: 'pass',
          note: 'Cart has items',
          source: 'system',
        },
        {
          checkName: 'Repayment History',
          result: 'pass',
          note: 'No overdue repayments',
          source: 'system',
        },
        {
          checkName: 'Contact Verification',
          result: 'pass',
          note: 'Phone and email are verified',
          source: 'system',
        },
      ],
    },
  },
  submit: {
    statusCode: 201,
    message: 'Loan application submitted successfully',
    data: {
      id: 'app-uuid-001',
      applicationRef: 'UBI-2026-AB3CD7E',
      userId: 'user-uuid-001',
      farmId: 'farm-uuid-001',
      status: 'Submitted',
      totalEstimatedValue: 61500,
      currency: 'NGN',
      purpose: 'Wet season maize planting',
      season: '2026 Wet Season',
      fulfillmentMethod: 'delivery',
      submittedAt: '2026-04-18T10:30:00.000Z',
      eligibility: { eligible: 'pass', blockingIssues: [], warnings: [] },
    },
  },
  submitFromMarketplace: {
    statusCode: 201,
    message: 'Loan application submitted successfully',
    data: {
      id: 'app-uuid-001',
      applicationRef: 'UBI-2026-AB3CD7E',
      userId: 'user-uuid-001',
      farmId: 'farm-uuid-001',
      status: 'Submitted',
      totalEstimatedValue: 61500,
      currency: 'NGN',
      purpose: 'Wet season maize planting',
      season: '2026 Wet Season',
      fulfillmentMethod: 'delivery',
      submittedAt: '2026-04-18T10:30:00.000Z',
      eligibility: { eligible: 'pass', blockingIssues: [], warnings: [] },
    },
  },
  getMyApplications: {
    statusCode: 200,
    message: 'Applications retrieved',
    data: [
      {
        id: 'app-uuid-001',
        applicationRef: 'UBI-2026-AB3CD7E',
        status: 'Submitted',
        totalEstimatedValue: 61500,
        submittedAt: '2026-04-18T10:30:00.000Z',
        farm: { name: 'Abubakar North Farm', state: 'Katsina' },
        items: [
          {
            id: 'item-uuid-001',
            resourceId: 'resource-uuid-001',
            itemName: 'Maize Seeds (OPV)',
            quantity: 5,
            unitPrice: 3500,
            totalAmount: 17500,
          },
          {
            id: 'item-uuid-002',
            resourceId: 'resource-uuid-002',
            itemName: 'Urea Fertilizer',
            quantity: 2,
            unitPrice: 22000,
            totalAmount: 44000,
          },
        ],
      },
    ],
    meta: { total: 1, page: 1, limit: 20, pages: 1 },
  },
  getPreviousLoansHistory: {
    statusCode: 200,
    message: 'Previous loans history retrieved',
    data: [
      {
        id: 'app-uuid-010',
        applicationRef: 'UBI-2026-K9L2M1N',
        status: 'Completed',
        totalEstimatedValue: 120000,
        currency: 'NGN',
        submittedAt: '2026-01-12T08:30:00.000Z',
        farm: { name: 'Abubakar North Farm', state: 'Katsina' },
        items: [
          {
            id: 'item-uuid-003',
            resourceId: 'resource-uuid-003',
            itemName: 'Hybrid Maize Seeds',
            quantity: 10,
            unitPrice: 4000,
            totalAmount: 40000,
          },
          {
            id: 'item-uuid-004',
            resourceId: 'resource-uuid-004',
            itemName: 'NPK Fertilizer',
            quantity: 4,
            unitPrice: 20000,
            totalAmount: 80000,
          },
        ],
        repaymentPlan: {
          totalRepaymentAmount: 126000,
          amountRepaid: 126000,
          outstandingBalance: 0,
          status: 'completed',
        },
      },
    ],
    meta: { total: 1, page: 1, limit: 20, pages: 1 },
  },
  getApplication: {
    statusCode: 200,
    message: 'Application retrieved',
    data: {
      id: 'app-uuid-001',
      applicationRef: 'UBI-2026-AB3CD7E',
      status: 'UnderReview',
      totalEstimatedValue: 61500,
      currency: 'NGN',
      purpose: 'Wet season maize planting',
      season: '2026 Wet Season',
      fulfillmentMethod: 'delivery',
      deliveryAddress: 'No 4 Kankia Road, Katsina',
      submittedAt: '2026-04-18T10:30:00.000Z',
      farm: {
        id: 'farm-uuid-001',
        name: 'Abubakar North Farm',
        state: 'Katsina',
        lga: 'Kankia',
        mainCropType: 'Maize',
        sizeValue: 5,
        sizeUnit: 'hectares',
        photos: [],
      },
      items: [
        {
          id: 'item-uuid-001',
          resourceId: 'resource-uuid-001',
          itemName: 'Maize Seeds (OPV)',
          quantity: 5,
          unitPrice: 3500,
          totalAmount: 17500,
        },
        {
          id: 'item-uuid-002',
          resourceId: 'resource-uuid-002',
          itemName: 'Urea Fertilizer',
          quantity: 2,
          unitPrice: 22000,
          totalAmount: 44000,
        },
      ],
      eligibilityChecks: [
        { checkName: 'KYC Verification', result: 'pass' },
        { checkName: 'Active Loan Conflict', result: 'pass' },
      ],
      decisions: [],
      statusHistory: [
        {
          toStatus: 'Submitted',
          changedBy: 'user-uuid-001',
          createdAt: '2026-04-18T10:30:00.000Z',
        },
        {
          toStatus: 'EligibilityReview',
          changedBy: 'system',
          createdAt: '2026-04-18T10:31:00.000Z',
        },
        {
          toStatus: 'UnderReview',
          changedBy: 'admin-uuid-001',
          createdAt: '2026-04-18T11:00:00.000Z',
        },
      ],
      fulfillment: null,
      repaymentPlan: null,
    },
  },
  getTimeline: {
    statusCode: 200,
    message: 'Timeline retrieved',
    data: [
      {
        id: 'hist-001',
        fromStatus: null,
        toStatus: 'Submitted',
        changedBy: 'user-uuid-001',
        reason: 'Application submitted by farmer',
        createdAt: '2026-04-18T10:30:00.000Z',
      },
      {
        id: 'hist-002',
        fromStatus: 'Submitted',
        toStatus: 'EligibilityReview',
        changedBy: 'system',
        reason: null,
        createdAt: '2026-04-18T10:31:00.000Z',
      },
      {
        id: 'hist-003',
        fromStatus: 'EligibilityReview',
        toStatus: 'UnderReview',
        changedBy: 'admin-uuid-001',
        reason: 'Passed eligibility checks',
        createdAt: '2026-04-18T11:00:00.000Z',
      },
    ],
  },
  getRepaymentSchedule: {
    statusCode: 200,
    message: 'Repayment schedule retrieved',
    data: {
      id: 'plan-uuid-001',
      applicationId: 'app-uuid-001',
      principalEquivalent: 61500,
      serviceCharge: 3075,
      totalRepaymentAmount: 64575,
      repaymentFrequency: 'monthly',
      numberOfInstallments: 6,
      installmentAmount: 10762.5,
      firstDueDate: '2026-10-01',
      amountRepaid: 0,
      outstandingBalance: 64575,
      status: 'pending',
      repayments: [
        {
          installmentNumber: 1,
          dueDate: '2026-10-01',
          amount: 10762.5,
          status: 'pending',
        },
        {
          installmentNumber: 2,
          dueDate: '2026-11-01',
          amount: 10762.5,
          status: 'pending',
        },
        {
          installmentNumber: 3,
          dueDate: '2026-12-01',
          amount: 10762.5,
          status: 'pending',
        },
        {
          installmentNumber: 4,
          dueDate: '2027-01-01',
          amount: 10762.5,
          status: 'pending',
        },
        {
          installmentNumber: 5,
          dueDate: '2027-02-01',
          amount: 10762.5,
          status: 'pending',
        },
        {
          installmentNumber: 6,
          dueDate: '2027-03-01',
          amount: 10762.5,
          status: 'pending',
        },
      ],
    },
  },
  cancel: {
    statusCode: 200,
    message: 'Application cancelled',
    data: null,
  },
} as const;
