export const marketplaceOrderResponse = {
  getCreditSummary: {
    status: true,
    message: 'Credit summary retrieved',
    data: {
      applicationRef: 'UBI-2026-AB3CD7E',
      approved: 61500,
      spent: 17500,
      available: 44000,
    },
  },
  placeOrder: {
    status: true,
    message: 'Marketplace order placed successfully',
    data: {
      id: 'order-uuid-001',
      orderRef: 'MKT-2026-AB3CD7',
      applicationId: 'app-uuid-001',
      userId: 'user-uuid-001',
      supplierId: null,
      totalAmount: 17500,
      status: 'pending',
      deliveryMethod: 'delivery',
      deliveryAddress: 'No 4 Kankia Road, Katsina',
      deliveryContact: '08012345678',
      pickupAddress: null,
      adminNote: null,
      receivedBy: null,
      deliveryProofUrl: null,
      deliveryNote: null,
      cancelReason: null,
      dispatchedAt: null,
      deliveredAt: null,
      cancelledAt: null,
      createdAt: '2026-04-24T10:30:00.000Z',
      updatedAt: '2026-04-24T10:30:00.000Z',
      items: [
        {
          id: 'item-uuid-001',
          orderId: 'order-uuid-001',
          resourceId: 'resource-uuid-001',
          itemName: 'Maize Seeds (OPV)',
          category: 'Seeds',
          unitPrice: 3500,
          quantity: 5,
          unitOfMeasure: 'kg',
          totalAmount: 17500,
          supplier: null,
        },
      ],
    },
  },
  listMyOrders: {
    status: true,
    message: 'Orders retrieved',
    data: [
      {
        id: 'order-uuid-001',
        orderRef: 'MKT-2026-AB3CD7',
        applicationId: 'app-uuid-001',
        userId: 'user-uuid-001',
        totalAmount: 17500,
        status: 'pending',
        deliveryMethod: 'delivery',
        deliveryAddress: 'No 4 Kankia Road, Katsina',
        createdAt: '2026-04-24T10:30:00.000Z',
        items: [
          {
            id: 'item-uuid-001',
            itemName: 'Maize Seeds (OPV)',
            quantity: 5,
            unitPrice: 3500,
            totalAmount: 17500,
          },
        ],
        supplier: null,
      },
    ],
    meta: { total: 1, page: 1, limit: 20, pages: 1 },
  },
  getMyOrder: {
    status: true,
    message: 'Order retrieved',
    data: {
      id: 'order-uuid-001',
      orderRef: 'MKT-2026-AB3CD7',
      applicationId: 'app-uuid-001',
      userId: 'user-uuid-001',
      totalAmount: 17500,
      status: 'pending',
      deliveryMethod: 'delivery',
      deliveryAddress: 'No 4 Kankia Road, Katsina',
      deliveryContact: '08012345678',
      adminNote: null,
      dispatchedAt: null,
      deliveredAt: null,
      cancelledAt: null,
      cancelReason: null,
      createdAt: '2026-04-24T10:30:00.000Z',
      updatedAt: '2026-04-24T10:30:00.000Z',
      items: [
        {
          id: 'item-uuid-001',
          itemName: 'Maize Seeds (OPV)',
          category: 'Seeds',
          unitPrice: 3500,
          quantity: 5,
          unitOfMeasure: 'kg',
          totalAmount: 17500,
          resource: {
            id: 'resource-uuid-001',
            name: 'Maize Seeds (OPV)',
            unitPrice: 3500,
            stockQuantity: 500,
          },
        },
      ],
      supplier: null,
    },
  },
  cancelMyOrder: {
    status: true,
    message: 'Order cancelled',
    data: null,
  },
} as const;
