export const marketplaceOrderAdminResponse = {
  listOrders: {
    status: true,
    message: 'Orders retrieved',
    data: [
      {
        id: 'order-uuid-001',
        orderRef: 'MKT-2026-AB3CD7',
        applicationId: 'app-uuid-001',
        userId: 'user-uuid-001',
        supplierId: null,
        totalAmount: 17500,
        status: 'pending',
        deliveryMethod: 'delivery',
        deliveryAddress: 'No 4 Kankia Road, Katsina',
        createdAt: '2026-04-24T10:30:00.000Z',
        items: [
          { id: 'item-uuid-001', itemName: 'Maize Seeds (OPV)', quantity: 5, unitPrice: 3500, totalAmount: 17500 },
        ],
        supplier: null,
        application: {
          id: 'app-uuid-001',
          applicationRef: 'UBI-2026-AB3CD7E',
          status: 'Approved',
        },
      },
    ],
    meta: { total: 1, page: 1, limit: 20, pages: 1 },
  },
  getOrderDetail: {
    status: true,
    message: 'Order retrieved',
    data: {
      id: 'order-uuid-001',
      orderRef: 'MKT-2026-AB3CD7',
      applicationId: 'app-uuid-001',
      userId: 'user-uuid-001',
      supplierId: 'supplier-uuid-001',
      totalAmount: 17500,
      status: 'confirmed',
      deliveryMethod: 'delivery',
      deliveryAddress: 'No 4 Kankia Road, Katsina',
      deliveryContact: '08012345678',
      adminNote: 'Supplier confirmed availability',
      dispatchedAt: null,
      deliveredAt: null,
      cancelledAt: null,
      cancelReason: null,
      createdAt: '2026-04-24T10:30:00.000Z',
      updatedAt: '2026-04-24T11:00:00.000Z',
      items: [
        {
          id: 'item-uuid-001',
          itemName: 'Maize Seeds (OPV)',
          category: 'Seeds',
          unitPrice: 3500,
          quantity: 5,
          unitOfMeasure: 'kg',
          totalAmount: 17500,
          supplier: 'AgroSupply Ltd',
          resource: {
            id: 'resource-uuid-001',
            name: 'Maize Seeds (OPV)',
            unitPrice: 3500,
            stockQuantity: 495,
          },
        },
      ],
      supplier: { id: 'supplier-uuid-001', name: 'AgroSupply Ltd', contactEmail: 'supply@agro.com' },
      application: {
        id: 'app-uuid-001',
        applicationRef: 'UBI-2026-AB3CD7E',
        status: 'Approved',
        userId: 'user-uuid-001',
      },
    },
  },
  confirmOrder: {
    status: true,
    message: 'Order confirmed and stock reserved',
    data: null,
  },
  packOrder: {
    status: true,
    message: 'Order marked as packed',
    data: null,
  },
  dispatchOrder: {
    status: true,
    message: 'Order dispatched',
    data: null,
  },
  deliverOrder: {
    status: true,
    message: 'Delivery recorded',
    data: null,
  },
  cancelOrder: {
    status: true,
    message: 'Order cancelled',
    data: null,
  },
} as const;
