export const fulfillmentResponse = {
  listFulfillments: {
    statusCode: 200,
    message: 'Fulfillments retrieved',
    data: [
      {
        id: 'ff-uuid-001',
        applicationId: 'app-uuid-001',
        status: 'dispatched',
        deliveryMethod: 'delivery',
        dispatchedAt: '2026-04-20T08:00:00.000Z',
        deliveredAt: null,
        supplier: { id: 'sup-uuid-001', name: 'AgroSupply Co.' },
        application: { applicationRef: 'UBI-2026-AB3CD7E' },
      },
    ],
    meta: { total: 1, page: 1, limit: 20, pages: 1 },
  },
  createFulfillment: {
    statusCode: 201,
    message: 'Fulfillment created',
    data: {
      id: 'ff-uuid-001',
      applicationId: 'app-uuid-001',
      supplierId: 'sup-uuid-001',
      status: 'pending',
      deliveryMethod: 'delivery',
      deliveryAddress: 'No 4 Kankia Road, Katsina',
      items: [
        {
          itemName: 'Maize Seeds (OPV)',
          quantity: 5,
          unitOfMeasure: 'bag',
          stockAvailable: true,
        },
        {
          itemName: 'Urea Fertilizer',
          quantity: 2,
          unitOfMeasure: 'bag',
          stockAvailable: true,
        },
      ],
    },
  },
  dispatch: {
    statusCode: 200,
    message: 'Dispatch recorded',
    data: null,
  },
  deliver: {
    statusCode: 200,
    message: 'Delivery recorded',
    data: null,
  },
  listSuppliers: {
    statusCode: 200,
    message: 'Suppliers retrieved',
    data: [
      {
        id: 'sup-uuid-001',
        name: 'AgroSupply Co.',
        location: 'Kano, Nigeria',
        contactPerson: 'Musa Ibrahim',
        contactPhone: '08012345678',
        deliveryCoverage: 'Kano, Katsina, Kaduna, Jigawa',
        isActive: true,
      },
    ],
  },
  createSupplier: {
    statusCode: 201,
    message: 'Supplier created',
    data: {
      id: 'sup-uuid-002',
      name: 'Delta AgroMart',
      location: 'Asaba, Delta State',
      latitude: 6.1848,
      longitude: 6.7423,
      contactPerson: 'Chukwuemeka Eze',
      contactPhone: '08023456789',
      isActive: true,
    },
  },
  getClosestSuppliers: {
    statusCode: 200,
    message: 'Closest suppliers retrieved',
    data: {
      farm: {
        id: 'farm-uuid-001',
        name: 'My Maize Farm',
        latitude: 12.9833,
        longitude: 7.6167,
      },
      suppliers: [
        {
          id: 'sup-uuid-001',
          name: 'AgroSupply Co.',
          location: 'Kano, Nigeria',
          latitude: 12.0022,
          longitude: 8.5919,
          distance: 145.32,
          distanceUnit: 'km',
          contactPerson: 'Musa Ibrahim',
          contactPhone: '08012345678',
          contactEmail: 'musa@agrosupply.com',
          deliveryCoverage: 'Kano, Katsina, Kaduna, Jigawa',
        },
        {
          id: 'sup-uuid-003',
          name: 'Katsina Agro Inputs',
          location: 'Katsina, Nigeria',
          latitude: 12.9948,
          longitude: 7.6016,
          distance: 12.45,
          distanceUnit: 'km',
          contactPerson: 'Ibrahim Yusuf',
          contactPhone: '08034567890',
          contactEmail: 'ibrahim@katsinaagro.com',
          deliveryCoverage: 'Katsina, Kaduna',
        },
      ],
    },
  },
} as const;
